<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "calendar"
 *
 * Auto generated by Extension Builder 2018-01-31
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'calendar',
    'description' => 'Extbase and Fluid calendar based on cal (TYPO3-extensions/cal)',
    'category' => 'plugin',
    'author' => 'Gregor Agnes',
    'author_email' => 'ga@zwo3.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
